apiVersion: v1
kind: Service
metadata:
  labels:
    service: flask-example
  name: flask-example
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: flask-example
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream backend {
        server 127.0.0.1:4000;
    }
    server {
        listen       80 default;
        location / {
          include uwsgi_params;
          uwsgi_pass backend;
        }
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: flask-example
  name: nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: flask-example
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      - image: backend
        imagePullPolicy: IfNotPresent
        name: backend
        resources: {}
      restartPolicy: Always
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
status: {}
